goblin and while for odd and even
poornima-ezhilmathi/Learning-Python pull request #5
Opened 2022-11-11 11:30 UTC by poornima-ezhilmathi

Leo, i have added the while loop for odd and even as a method in the same scripts alone with goblin program. please refer.
Thank you for your time.

2022-11-11 12:08 UTC, leocyriac requested changes
Apart from the inline comments. Please separate out the odd even programs by the type of loop. It doesn't make sense to have the same program printing the same set of numbers twice. This git repository should be something for you to refer back or show to somebody as a programming portfolio.

2022-11-11 12:08 UTC, leocyriac commented on goblin_hunt.py
> +    while i<=5:
User is getting only 6 chances. Is that a right thing to do?

2022-11-11 12:08 UTC, leocyriac commented on goblin_hunt.py
> +    print("Stephen, do you think you can find the goblin hiding in the kitchen cupboards?")
This needs to be correctd.

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/38807024/201337051-7554e9a0-3680-42e3-9ea0-da6c67ab2009.png">

2022-11-12 09:16 UTC, leocyriac commented on goblin_hunt.py
> +            False
what's this doing here?

2022-11-12 09:17 UTC, leocyriac approved these changes
Looks good. Don't merge Goblin.. we will modify it in our next class

2022-11-12 09:55 UTC, poornima-ezhilmathi commented on goblin_hunt.py
> +            False
i removed false, this is not necessary

2022-11-18 04:54 UTC, closed without merging